### ISSUE TITLE
JSON file vs. file naming

### ISSUE THREAD

**Issue by neuhaus** [francoislaberge/mary-gearvr#1]
I think the JSON file is no longer required for more recent versions of MilkVR, instead the filename needs to have special suffixes that tell the viewer how to render it.

The suffixes are described at https://milkvr.com/#/content/faq

**Comment by seflless** [comment]
Thanks for the heads up. This project is unmaintained now. So I won't be updating it, but I definitely will use that information soon for something else I'm working on. Thanks!
